<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TradingResearchEngine.Application\TradingResearchEngine.Application.csproj" />
    <ProjectReference Include="..\TradingResearchEngine.Infrastructure\TradingResearchEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9cd08e70-92db-4614-a26c-9aa4e8aadd6e</UserSecretsId>
  </PropertyGroup>

</Project>
