using System.Globalization;
using System.Text;
using TradingResearchEngine.Application.Strategy.Composite;
using TradingResearchEngine.Application.Strategy.Composite.Conditions;

namespace TradingResearchEngine.Infrastructure.Export;

/// <summary>
/// Shared helper for translating composite strategy configurations to platform-specific code.
/// Provides static methods for MQL4, MQL5, and PineScript code generation.
/// </summary>
public static class CompositeExportHelper
{
    /// <summary>
    /// Generates MQL4 Expert Advisor code from a composite strategy configuration.
    /// </summary>
    public static (string Code, List<string> Warnings) GenerateMQL4(CompositeStrategyConfig config)
    {
        var warnings = new List<string>();
        var sb = new StringBuilder();

        sb.AppendLine("//+------------------------------------------------------------------+");
        sb.AppendLine($"//| {config.Name} EA (Composite)                                      |");
        sb.AppendLine("//| Generated by TradingResearchEngine                                |");
        sb.AppendLine("//+------------------------------------------------------------------+");
        sb.AppendLine("#property strict");
        sb.AppendLine();
        sb.AppendLine("// NOTE: Composite strategy export — signal timing may differ from backtest");
        sb.AppendLine("input double LotSize = 0.1;");
        sb.AppendLine();

        // Declare indicator variables
        foreach (var ind in config.Indicators)
        {
            var varDecls = GetMQL4IndicatorDeclarations(ind, warnings);
            foreach (var decl in varDecls)
                sb.AppendLine(decl);
        }

        sb.AppendLine();
        sb.AppendLine("int OnInit()");
        sb.AppendLine("{");
        sb.AppendLine("    return INIT_SUCCEEDED;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void OnDeinit(const int reason)");
        sb.AppendLine("{");
        sb.AppendLine("    // Cleanup");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void OnTick()");
        sb.AppendLine("{");

        // Compute indicator values
        foreach (var ind in config.Indicators)
        {
            var computeLines = GetMQL4IndicatorComputation(ind, warnings);
            foreach (var line in computeLines)
                sb.AppendLine($"    {line}");
        }

        sb.AppendLine();

        // Parse and translate entry condition
        var entryExpr = TranslateConditionMQL(config.EntryCondition, config.Indicators, warnings);
        var exitExpr = TranslateConditionMQL(config.ExitCondition, config.Indicators, warnings);

        sb.AppendLine($"    // Entry condition");
        sb.AppendLine($"    bool entrySignal = {entryExpr};");
        sb.AppendLine($"    // Exit condition");
        sb.AppendLine($"    bool exitSignal = {exitExpr};");
        sb.AppendLine();
        sb.AppendLine("    if (entrySignal && OrdersTotal() == 0)");
        sb.AppendLine("    {");
        sb.AppendLine($"        OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, \"{config.Name}\", 0, 0, clrGreen);");
        sb.AppendLine("    }");
        sb.AppendLine("    else if (exitSignal && OrdersTotal() > 0)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (int i = OrdersTotal() - 1; i >= 0; i--)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())");
        sb.AppendLine("                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (sb.ToString(), warnings);
    }

    /// <summary>
    /// Generates MQL5 Expert Advisor code from a composite strategy configuration.
    /// </summary>
    public static (string Code, List<string> Warnings) GenerateMQL5(CompositeStrategyConfig config)
    {
        var warnings = new List<string>();
        var sb = new StringBuilder();

        sb.AppendLine("//+------------------------------------------------------------------+");
        sb.AppendLine($"//| {config.Name} EA (Composite, MQL5)                                |");
        sb.AppendLine("//| Generated by TradingResearchEngine                                |");
        sb.AppendLine("//+------------------------------------------------------------------+");
        sb.AppendLine("#property strict");
        sb.AppendLine("#include <Trade\\Trade.mqh>");
        sb.AppendLine();
        sb.AppendLine("// NOTE: Composite strategy export — signal timing may differ from backtest");
        sb.AppendLine("input double LotSize = 0.1;");
        sb.AppendLine();
        sb.AppendLine("CTrade trade;");

        // Declare indicator handles
        foreach (var ind in config.Indicators)
        {
            var handleDecls = GetMQL5HandleDeclarations(ind, warnings);
            foreach (var decl in handleDecls)
                sb.AppendLine(decl);
        }

        sb.AppendLine();
        sb.AppendLine("int OnInit()");
        sb.AppendLine("{");

        // Initialize indicator handles
        foreach (var ind in config.Indicators)
        {
            var initLines = GetMQL5HandleInit(ind, warnings);
            foreach (var line in initLines)
                sb.AppendLine($"    {line}");
        }

        sb.AppendLine("    return INIT_SUCCEEDED;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void OnDeinit(const int reason)");
        sb.AppendLine("{");

        // Release indicator handles
        foreach (var ind in config.Indicators)
        {
            var releaseLines = GetMQL5HandleRelease(ind);
            foreach (var line in releaseLines)
                sb.AppendLine($"    {line}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void OnTick()");
        sb.AppendLine("{");

        // Copy indicator buffers
        foreach (var ind in config.Indicators)
        {
            var copyLines = GetMQL5BufferCopy(ind, warnings);
            foreach (var line in copyLines)
                sb.AppendLine($"    {line}");
        }

        sb.AppendLine();

        // Parse and translate entry/exit conditions
        var entryExpr = TranslateConditionMQL(config.EntryCondition, config.Indicators, warnings);
        var exitExpr = TranslateConditionMQL(config.ExitCondition, config.Indicators, warnings);

        sb.AppendLine($"    // Entry condition");
        sb.AppendLine($"    bool entrySignal = {entryExpr};");
        sb.AppendLine($"    // Exit condition");
        sb.AppendLine($"    bool exitSignal = {exitExpr};");
        sb.AppendLine();
        sb.AppendLine("    if (entrySignal && PositionsTotal() == 0)");
        sb.AppendLine("    {");
        sb.AppendLine($"        trade.Buy(LotSize, Symbol(), 0, 0, 0, \"{config.Name}\");");
        sb.AppendLine("    }");
        sb.AppendLine("    else if (exitSignal && PositionsTotal() > 0)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (int i = PositionsTotal() - 1; i >= 0; i--)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (PositionGetSymbol(i) == Symbol())");
        sb.AppendLine("                trade.PositionClose(PositionGetTicket(i));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void OnTrade()");
        sb.AppendLine("{");
        sb.AppendLine("    // Trade event handler for position management");
        sb.AppendLine("}");

        return (sb.ToString(), warnings);
    }

    /// <summary>
    /// Generates Pine Script v6 code from a composite strategy configuration.
    /// </summary>
    public static (string Code, List<string> Warnings) GeneratePineScript(CompositeStrategyConfig config)
    {
        var warnings = new List<string>();
        var sb = new StringBuilder();

        sb.AppendLine("//@version=6");
        sb.AppendLine($"// {config.Name} (Composite Strategy)");
        sb.AppendLine("// Generated by TradingResearchEngine");
        sb.AppendLine("// NOTE: Composite strategy export — signal timing aligns with bar close");
        sb.AppendLine($"strategy(\"{config.Name}\", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)");
        sb.AppendLine();

        // Declare indicator variables
        foreach (var ind in config.Indicators)
        {
            var pineLines = GetPineScriptIndicatorDeclaration(ind, warnings);
            foreach (var line in pineLines)
                sb.AppendLine(line);
        }

        sb.AppendLine();

        // Parse and translate entry/exit conditions
        var entryExpr = TranslateConditionPineScript(config.EntryCondition, config.Indicators, warnings);
        var exitExpr = TranslateConditionPineScript(config.ExitCondition, config.Indicators, warnings);

        sb.AppendLine($"// Entry condition");
        sb.AppendLine($"longCondition = {entryExpr}");
        sb.AppendLine($"// Exit condition");
        sb.AppendLine($"exitCondition = {exitExpr}");
        sb.AppendLine();
        sb.AppendLine("if longCondition");
        sb.AppendLine("    strategy.entry(\"Long\", strategy.long)");
        sb.AppendLine();
        sb.AppendLine("if exitCondition");
        sb.AppendLine("    strategy.close(\"Long\")");

        return (sb.ToString(), warnings);
    }

    #region MQL4 Indicator Helpers

    private static List<string> GetMQL4IndicatorDeclarations(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();

        switch (type)
        {
            case "sma":
            case "ema":
            case "rsi":
            case "atr":
                // Single-value indicators: current and previous
                break;
            case "macd":
                // Multi-value: main, signal, histogram
                break;
            case "bollinger":
                // Multi-value: upper, middle, lower
                break;
            case "stochastic":
                // Multi-value: K, D
                break;
            case "donchian":
                // Multi-value: upper, lower
                break;
            default:
                warnings.Add($"Unsupported indicator type '{ind.Type}' for MQL4 export.");
                break;
        }

        return lines;
    }

    private static List<string> GetMQL4IndicatorComputation(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();
        var period = GetIntParam(ind.Parameters, "period", 14);

        switch (type)
        {
            case "sma":
                lines.Add($"double {ind.Id}_0 = iMA(Symbol(), 0, {period}, 0, MODE_SMA, PRICE_CLOSE, 0);");
                lines.Add($"double {ind.Id}_1 = iMA(Symbol(), 0, {period}, 0, MODE_SMA, PRICE_CLOSE, 1);");
                break;
            case "ema":
                lines.Add($"double {ind.Id}_0 = iMA(Symbol(), 0, {period}, 0, MODE_EMA, PRICE_CLOSE, 0);");
                lines.Add($"double {ind.Id}_1 = iMA(Symbol(), 0, {period}, 0, MODE_EMA, PRICE_CLOSE, 1);");
                break;
            case "rsi":
                lines.Add($"double {ind.Id}_0 = iRSI(Symbol(), 0, {period}, PRICE_CLOSE, 0);");
                lines.Add($"double {ind.Id}_1 = iRSI(Symbol(), 0, {period}, PRICE_CLOSE, 1);");
                break;
            case "atr":
                lines.Add($"double {ind.Id}_0 = iATR(Symbol(), 0, {period}, 0);");
                lines.Add($"double {ind.Id}_1 = iATR(Symbol(), 0, {period}, 1);");
                break;
            case "macd":
            {
                var fast = GetIntParam(ind.Parameters, "fastPeriod", 12);
                var slow = GetIntParam(ind.Parameters, "slowPeriod", 26);
                var signal = GetIntParam(ind.Parameters, "signalPeriod", 9);
                lines.Add($"double {ind.Id}_Macd_0 = iMACD(Symbol(), 0, {fast}, {slow}, {signal}, PRICE_CLOSE, MODE_MAIN, 0);");
                lines.Add($"double {ind.Id}_Macd_1 = iMACD(Symbol(), 0, {fast}, {slow}, {signal}, PRICE_CLOSE, MODE_MAIN, 1);");
                lines.Add($"double {ind.Id}_Signal_0 = iMACD(Symbol(), 0, {fast}, {slow}, {signal}, PRICE_CLOSE, MODE_SIGNAL, 0);");
                lines.Add($"double {ind.Id}_Signal_1 = iMACD(Symbol(), 0, {fast}, {slow}, {signal}, PRICE_CLOSE, MODE_SIGNAL, 1);");
                lines.Add($"double {ind.Id}_Histogram_0 = {ind.Id}_Macd_0 - {ind.Id}_Signal_0;");
                lines.Add($"double {ind.Id}_Histogram_1 = {ind.Id}_Macd_1 - {ind.Id}_Signal_1;");
                break;
            }
            case "bollinger":
            {
                var stdDev = GetDecimalParam(ind.Parameters, "standardDeviations", 2.0m);
                lines.Add($"double {ind.Id}_Upper_0 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_UPPER, 0);");
                lines.Add($"double {ind.Id}_Upper_1 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_UPPER, 1);");
                lines.Add($"double {ind.Id}_Middle_0 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_MAIN, 0);");
                lines.Add($"double {ind.Id}_Middle_1 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_MAIN, 1);");
                lines.Add($"double {ind.Id}_Lower_0 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_LOWER, 0);");
                lines.Add($"double {ind.Id}_Lower_1 = iBands(Symbol(), 0, {period}, {Fmt(stdDev)}, 0, PRICE_CLOSE, MODE_LOWER, 1);");
                break;
            }
            case "stochastic":
            {
                var kPeriod = GetIntParam(ind.Parameters, "kPeriod", 14);
                var dPeriod = GetIntParam(ind.Parameters, "dPeriod", 3);
                var slowing = GetIntParam(ind.Parameters, "slowing", 3);
                lines.Add($"double {ind.Id}_K_0 = iStochastic(Symbol(), 0, {kPeriod}, {dPeriod}, {slowing}, MODE_SMA, 0, MODE_MAIN, 0);");
                lines.Add($"double {ind.Id}_K_1 = iStochastic(Symbol(), 0, {kPeriod}, {dPeriod}, {slowing}, MODE_SMA, 0, MODE_MAIN, 1);");
                lines.Add($"double {ind.Id}_D_0 = iStochastic(Symbol(), 0, {kPeriod}, {dPeriod}, {slowing}, MODE_SMA, 0, MODE_SIGNAL, 0);");
                lines.Add($"double {ind.Id}_D_1 = iStochastic(Symbol(), 0, {kPeriod}, {dPeriod}, {slowing}, MODE_SMA, 0, MODE_SIGNAL, 1);");
                break;
            }
            case "donchian":
            {
                lines.Add($"double {ind.Id}_Upper_0 = High[iHighest(Symbol(), 0, MODE_HIGH, {period}, 1)];");
                lines.Add($"double {ind.Id}_Upper_1 = High[iHighest(Symbol(), 0, MODE_HIGH, {period}, 2)];");
                lines.Add($"double {ind.Id}_Lower_0 = Low[iLowest(Symbol(), 0, MODE_LOW, {period}, 1)];");
                lines.Add($"double {ind.Id}_Lower_1 = Low[iLowest(Symbol(), 0, MODE_LOW, {period}, 2)];");
                break;
            }
            default:
                lines.Add($"// NOTE: Unsupported indicator type '{ind.Type}'");
                break;
        }

        return lines;
    }

    #endregion

    #region MQL5 Indicator Helpers

    private static List<string> GetMQL5HandleDeclarations(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();

        switch (type)
        {
            case "sma":
            case "ema":
            case "rsi":
            case "atr":
                lines.Add($"int handle_{ind.Id};");
                break;
            case "macd":
                lines.Add($"int handle_{ind.Id};");
                break;
            case "bollinger":
                lines.Add($"int handle_{ind.Id};");
                break;
            case "stochastic":
                lines.Add($"int handle_{ind.Id};");
                break;
            case "donchian":
                // Donchian is computed manually in MQL5
                break;
            default:
                warnings.Add($"Unsupported indicator type '{ind.Type}' for MQL5 export.");
                break;
        }

        return lines;
    }

    private static List<string> GetMQL5HandleInit(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();
        var period = GetIntParam(ind.Parameters, "period", 14);

        switch (type)
        {
            case "sma":
                lines.Add($"handle_{ind.Id} = iMA(Symbol(), PERIOD_CURRENT, {period}, 0, MODE_SMA, PRICE_CLOSE);");
                break;
            case "ema":
                lines.Add($"handle_{ind.Id} = iMA(Symbol(), PERIOD_CURRENT, {period}, 0, MODE_EMA, PRICE_CLOSE);");
                break;
            case "rsi":
                lines.Add($"handle_{ind.Id} = iRSI(Symbol(), PERIOD_CURRENT, {period}, PRICE_CLOSE);");
                break;
            case "atr":
                lines.Add($"handle_{ind.Id} = iATR(Symbol(), PERIOD_CURRENT, {period});");
                break;
            case "macd":
            {
                var fast = GetIntParam(ind.Parameters, "fastPeriod", 12);
                var slow = GetIntParam(ind.Parameters, "slowPeriod", 26);
                var signal = GetIntParam(ind.Parameters, "signalPeriod", 9);
                lines.Add($"handle_{ind.Id} = iMACD(Symbol(), PERIOD_CURRENT, {fast}, {slow}, {signal}, PRICE_CLOSE);");
                break;
            }
            case "bollinger":
            {
                var stdDev = GetDecimalParam(ind.Parameters, "standardDeviations", 2.0m);
                lines.Add($"handle_{ind.Id} = iBands(Symbol(), PERIOD_CURRENT, {period}, 0, {Fmt(stdDev)}, PRICE_CLOSE);");
                break;
            }
            case "stochastic":
            {
                var kPeriod = GetIntParam(ind.Parameters, "kPeriod", 14);
                var dPeriod = GetIntParam(ind.Parameters, "dPeriod", 3);
                var slowing = GetIntParam(ind.Parameters, "slowing", 3);
                lines.Add($"handle_{ind.Id} = iStochastic(Symbol(), PERIOD_CURRENT, {kPeriod}, {dPeriod}, {slowing}, MODE_SMA, STO_LOWHIGH);");
                break;
            }
            case "donchian":
                // Computed manually
                break;
            default:
                lines.Add($"// NOTE: Unsupported indicator type '{ind.Type}'");
                break;
        }

        return lines;
    }

    private static List<string> GetMQL5HandleRelease(IndicatorConfig ind)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();

        if (type is "sma" or "ema" or "rsi" or "atr" or "macd" or "bollinger" or "stochastic")
        {
            lines.Add($"IndicatorRelease(handle_{ind.Id});");
        }

        return lines;
    }

    private static List<string> GetMQL5BufferCopy(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();
        var period = GetIntParam(ind.Parameters, "period", 14);

        switch (type)
        {
            case "sma":
            case "ema":
            case "rsi":
            case "atr":
                lines.Add($"double {ind.Id}_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 0, 0, 2, {ind.Id}_buf);");
                break;
            case "macd":
                lines.Add($"double {ind.Id}_Macd_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 0, 0, 2, {ind.Id}_Macd_buf);");
                lines.Add($"double {ind.Id}_Signal_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 1, 0, 2, {ind.Id}_Signal_buf);");
                break;
            case "bollinger":
                lines.Add($"double {ind.Id}_Middle_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 0, 0, 2, {ind.Id}_Middle_buf);");
                lines.Add($"double {ind.Id}_Upper_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 1, 0, 2, {ind.Id}_Upper_buf);");
                lines.Add($"double {ind.Id}_Lower_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 2, 0, 2, {ind.Id}_Lower_buf);");
                break;
            case "stochastic":
                lines.Add($"double {ind.Id}_K_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 0, 0, 2, {ind.Id}_K_buf);");
                lines.Add($"double {ind.Id}_D_buf[2];");
                lines.Add($"CopyBuffer(handle_{ind.Id}, 1, 0, 2, {ind.Id}_D_buf);");
                break;
            case "donchian":
            {
                lines.Add($"double {ind.Id}_Upper_0 = 0, {ind.Id}_Lower_0 = DBL_MAX;");
                lines.Add($"double {ind.Id}_Upper_1 = 0, {ind.Id}_Lower_1 = DBL_MAX;");
                lines.Add($"for (int i = 1; i <= {period}; i++) {{ double h = iHigh(Symbol(), PERIOD_CURRENT, i); double l = iLow(Symbol(), PERIOD_CURRENT, i); if (h > {ind.Id}_Upper_0) {ind.Id}_Upper_0 = h; if (l < {ind.Id}_Lower_0) {ind.Id}_Lower_0 = l; }}");
                lines.Add($"for (int i = 2; i <= {period} + 1; i++) {{ double h = iHigh(Symbol(), PERIOD_CURRENT, i); double l = iLow(Symbol(), PERIOD_CURRENT, i); if (h > {ind.Id}_Upper_1) {ind.Id}_Upper_1 = h; if (l < {ind.Id}_Lower_1) {ind.Id}_Lower_1 = l; }}");
                break;
            }
            default:
                lines.Add($"// NOTE: Unsupported indicator type '{ind.Type}'");
                break;
        }

        return lines;
    }

    #endregion

    #region PineScript Indicator Helpers

    private static List<string> GetPineScriptIndicatorDeclaration(IndicatorConfig ind, List<string> warnings)
    {
        var lines = new List<string>();
        var type = ind.Type.ToLowerInvariant();
        var period = GetIntParam(ind.Parameters, "period", 14);

        switch (type)
        {
            case "sma":
                lines.Add($"{ind.Id} = ta.sma(close, {period})");
                break;
            case "ema":
                lines.Add($"{ind.Id} = ta.ema(close, {period})");
                break;
            case "rsi":
                lines.Add($"{ind.Id} = ta.rsi(close, {period})");
                break;
            case "atr":
                lines.Add($"{ind.Id} = ta.atr({period})");
                break;
            case "macd":
            {
                var fast = GetIntParam(ind.Parameters, "fastPeriod", 12);
                var slow = GetIntParam(ind.Parameters, "slowPeriod", 26);
                var signal = GetIntParam(ind.Parameters, "signalPeriod", 9);
                lines.Add($"[{ind.Id}_Macd, {ind.Id}_Signal, {ind.Id}_Histogram] = ta.macd(close, {fast}, {slow}, {signal})");
                break;
            }
            case "bollinger":
            {
                var stdDev = GetDecimalParam(ind.Parameters, "standardDeviations", 2.0m);
                lines.Add($"[{ind.Id}_Middle, {ind.Id}_Upper, {ind.Id}_Lower] = ta.bb(close, {period}, {Fmt(stdDev)})");
                break;
            }
            case "stochastic":
            {
                var kPeriod = GetIntParam(ind.Parameters, "kPeriod", 14);
                var dPeriod = GetIntParam(ind.Parameters, "dPeriod", 3);
                var slowing = GetIntParam(ind.Parameters, "slowing", 3);
                lines.Add($"{ind.Id}_K = ta.stoch(close, high, low, {kPeriod})");
                lines.Add($"{ind.Id}_D = ta.sma({ind.Id}_K, {dPeriod})");
                break;
            }
            case "donchian":
                lines.Add($"{ind.Id}_Upper = ta.highest(high, {period})[1]");
                lines.Add($"{ind.Id}_Lower = ta.lowest(low, {period})[1]");
                break;
            default:
                warnings.Add($"Unsupported indicator type '{ind.Type}' for PineScript export.");
                lines.Add($"// NOTE: Unsupported indicator type '{ind.Type}'");
                break;
        }

        return lines;
    }

    #endregion

    #region Condition Translation

    private static string TranslateConditionMQL(
        string conditionExpression,
        IReadOnlyList<IndicatorConfig> indicators,
        List<string> warnings)
    {
        try
        {
            var ast = ConditionParser.Parse(conditionExpression);
            return TranslateNodeMQL(ast, indicators, warnings);
        }
        catch (Exception ex)
        {
            warnings.Add($"Failed to parse condition '{conditionExpression}': {ex.Message}");
            return "false /* parse error */";
        }
    }

    private static string TranslateNodeMQL(ConditionNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        return node switch
        {
            LogicalNode logical => TranslateLogicalMQL(logical, indicators, warnings),
            ComparisonNode comparison => TranslateComparisonMQL(comparison, indicators, warnings),
            CrossNode cross => TranslateCrossMQL(cross, indicators, warnings),
            _ => "false /* unsupported node */"
        };
    }

    private static string TranslateLogicalMQL(LogicalNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var left = TranslateNodeMQL(node.Left, indicators, warnings);
        var right = TranslateNodeMQL(node.Right, indicators, warnings);
        var op = node.Operator == LogicalOperator.And ? "&&" : "||";
        return $"({left} {op} {right})";
    }

    private static string TranslateComparisonMQL(ComparisonNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var left = TranslateValueMQL(node.Left, indicators, warnings, current: true);
        var right = TranslateValueMQL(node.Right, indicators, warnings, current: true);
        var op = node.Operator switch
        {
            ComparisonOperator.GreaterThan => ">",
            ComparisonOperator.LessThan => "<",
            ComparisonOperator.GreaterThanOrEqual => ">=",
            ComparisonOperator.LessThanOrEqual => "<=",
            ComparisonOperator.Equal => "==",
            ComparisonOperator.NotEqual => "!=",
            _ => "=="
        };
        return $"{left} {op} {right}";
    }

    private static string TranslateCrossMQL(CrossNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var leftCurrent = TranslateValueMQL(node.Left, indicators, warnings, current: true);
        var rightCurrent = TranslateValueMQL(node.Right, indicators, warnings, current: true);
        var leftPrev = TranslateValueMQL(node.Left, indicators, warnings, current: false);
        var rightPrev = TranslateValueMQL(node.Right, indicators, warnings, current: false);

        if (node.Direction == CrossDirection.Above)
        {
            return $"({leftCurrent} > {rightCurrent} && {leftPrev} <= {rightPrev})";
        }
        else
        {
            return $"({leftCurrent} < {rightCurrent} && {leftPrev} >= {rightPrev})";
        }
    }

    private static string TranslateValueMQL(ValueNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings, bool current)
    {
        var shift = current ? "0" : "1";

        switch (node)
        {
            case LiteralNode literal:
                return literal.Value.ToString(CultureInfo.InvariantCulture);

            case PriceRefNode price:
                return price.Field switch
                {
                    PriceField.Open => $"Open[{shift}]",
                    PriceField.High => $"High[{shift}]",
                    PriceField.Low => $"Low[{shift}]",
                    PriceField.Close => $"Close[{shift}]",
                    PriceField.Volume => $"Volume[{shift}]",
                    _ => $"Close[{shift}]"
                };

            case IndicatorRefNode indRef:
                return GetMQLIndicatorVariable(indRef, indicators, current, warnings);

            default:
                return "0";
        }
    }

    private static string GetMQLIndicatorVariable(IndicatorRefNode indRef, IReadOnlyList<IndicatorConfig> indicators, bool current, List<string> warnings)
    {
        var suffix = current ? "_0" : "_1";
        var ind = indicators.FirstOrDefault(i => string.Equals(i.Id, indRef.IndicatorId, StringComparison.OrdinalIgnoreCase));

        if (ind is null)
        {
            warnings.Add($"Unknown indicator reference '{indRef.IndicatorId}' in condition.");
            return $"0 /* unknown: {indRef.IndicatorId} */";
        }

        var type = ind.Type.ToLowerInvariant();

        // Handle sub-properties for multi-value indicators
        if (indRef.SubProperty is not null)
        {
            var sub = indRef.SubProperty;

            // For MQL5 buffer-based access, use _buf[0] or _buf[1]
            // For MQL4, we use the pre-computed variables
            return type switch
            {
                "macd" => $"{ind.Id}_{sub}{suffix}",
                "bollinger" => $"{ind.Id}_{sub}{suffix}",
                "stochastic" => $"{ind.Id}_{sub}{suffix}",
                "donchian" => $"{ind.Id}_{sub}{suffix}",
                _ => $"{ind.Id}{suffix}"
            };
        }

        // Single-value indicators
        return type switch
        {
            "sma" or "ema" or "rsi" or "atr" => $"{ind.Id}{suffix}",
            "macd" => $"{ind.Id}_Macd{suffix}",
            "bollinger" => $"{ind.Id}_Middle{suffix}",
            "stochastic" => $"{ind.Id}_K{suffix}",
            "donchian" => $"{ind.Id}_Upper{suffix}",
            _ => $"{ind.Id}{suffix}"
        };
    }

    private static string TranslateConditionPineScript(
        string conditionExpression,
        IReadOnlyList<IndicatorConfig> indicators,
        List<string> warnings)
    {
        try
        {
            var ast = ConditionParser.Parse(conditionExpression);
            return TranslateNodePineScript(ast, indicators, warnings);
        }
        catch (Exception ex)
        {
            warnings.Add($"Failed to parse condition '{conditionExpression}': {ex.Message}");
            return "false // parse error";
        }
    }

    private static string TranslateNodePineScript(ConditionNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        return node switch
        {
            LogicalNode logical => TranslateLogicalPineScript(logical, indicators, warnings),
            ComparisonNode comparison => TranslateComparisonPineScript(comparison, indicators, warnings),
            CrossNode cross => TranslateCrossPineScript(cross, indicators, warnings),
            _ => "false // unsupported node"
        };
    }

    private static string TranslateLogicalPineScript(LogicalNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var left = TranslateNodePineScript(node.Left, indicators, warnings);
        var right = TranslateNodePineScript(node.Right, indicators, warnings);
        var op = node.Operator == LogicalOperator.And ? "and" : "or";
        return $"({left} {op} {right})";
    }

    private static string TranslateComparisonPineScript(ComparisonNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var left = TranslateValuePineScript(node.Left, indicators, warnings);
        var right = TranslateValuePineScript(node.Right, indicators, warnings);
        var op = node.Operator switch
        {
            ComparisonOperator.GreaterThan => ">",
            ComparisonOperator.LessThan => "<",
            ComparisonOperator.GreaterThanOrEqual => ">=",
            ComparisonOperator.LessThanOrEqual => "<=",
            ComparisonOperator.Equal => "==",
            ComparisonOperator.NotEqual => "!=",
            _ => "=="
        };
        return $"{left} {op} {right}";
    }

    private static string TranslateCrossPineScript(CrossNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var left = TranslateValuePineScript(node.Left, indicators, warnings);
        var right = TranslateValuePineScript(node.Right, indicators, warnings);

        return node.Direction == CrossDirection.Above
            ? $"ta.crossover({left}, {right})"
            : $"ta.crossunder({left}, {right})";
    }

    private static string TranslateValuePineScript(ValueNode node, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        switch (node)
        {
            case LiteralNode literal:
                return literal.Value.ToString(CultureInfo.InvariantCulture);

            case PriceRefNode price:
                return price.Field switch
                {
                    PriceField.Open => "open",
                    PriceField.High => "high",
                    PriceField.Low => "low",
                    PriceField.Close => "close",
                    PriceField.Volume => "volume",
                    _ => "close"
                };

            case IndicatorRefNode indRef:
                return GetPineScriptIndicatorVariable(indRef, indicators, warnings);

            default:
                return "0";
        }
    }

    private static string GetPineScriptIndicatorVariable(IndicatorRefNode indRef, IReadOnlyList<IndicatorConfig> indicators, List<string> warnings)
    {
        var ind = indicators.FirstOrDefault(i => string.Equals(i.Id, indRef.IndicatorId, StringComparison.OrdinalIgnoreCase));

        if (ind is null)
        {
            warnings.Add($"Unknown indicator reference '{indRef.IndicatorId}' in condition.");
            return $"0 // unknown: {indRef.IndicatorId}";
        }

        var type = ind.Type.ToLowerInvariant();

        // Handle sub-properties
        if (indRef.SubProperty is not null)
        {
            var sub = indRef.SubProperty;
            return type switch
            {
                "macd" => $"{ind.Id}_{sub}",
                "bollinger" => $"{ind.Id}_{sub}",
                "stochastic" => $"{ind.Id}_{sub}",
                "donchian" => $"{ind.Id}_{sub}",
                _ => ind.Id
            };
        }

        // Single-value indicators use their ID directly
        return type switch
        {
            "sma" or "ema" or "rsi" or "atr" => ind.Id,
            "macd" => $"{ind.Id}_Macd",
            "bollinger" => $"{ind.Id}_Middle",
            "stochastic" => $"{ind.Id}_K",
            "donchian" => $"{ind.Id}_Upper",
            _ => ind.Id
        };
    }

    #endregion

    #region Parameter Helpers

    private static int GetIntParam(IReadOnlyDictionary<string, object>? parameters, string key, int defaultValue)
    {
        if (parameters is null || !parameters.TryGetValue(key, out var value))
            return defaultValue;

        return value switch
        {
            int i => i,
            long l => (int)l,
            double d => (int)d,
            decimal dec => (int)dec,
            string s when int.TryParse(s, out var parsed) => parsed,
            System.Text.Json.JsonElement je when je.TryGetInt32(out var ji) => ji,
            _ => defaultValue
        };
    }

    private static decimal GetDecimalParam(IReadOnlyDictionary<string, object>? parameters, string key, decimal defaultValue)
    {
        if (parameters is null || !parameters.TryGetValue(key, out var value))
            return defaultValue;

        return value switch
        {
            decimal d => d,
            double dbl => (decimal)dbl,
            float f => (decimal)f,
            int i => i,
            long l => l,
            string s when decimal.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed) => parsed,
            System.Text.Json.JsonElement je when je.TryGetDecimal(out var jd) => jd,
            _ => defaultValue
        };
    }

    private static string Fmt(decimal value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>
    /// Attempts to extract a <see cref="CompositeStrategyConfig"/> from a StrategyVersion's Parameters dictionary.
    /// Returns null if the parameters do not contain a valid composite config.
    /// </summary>
    public static CompositeStrategyConfig? ExtractCompositeConfig(Dictionary<string, object> parameters)
    {
        if (parameters.TryGetValue("compositeConfig", out var configObj))
        {
            if (configObj is System.Text.Json.JsonElement je)
            {
                try
                {
                    return System.Text.Json.JsonSerializer.Deserialize<CompositeStrategyConfig>(
                        je.GetRawText(),
                        new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                }
                catch
                {
                    return null;
                }
            }

            if (configObj is CompositeStrategyConfig config)
                return config;
        }

        // Try to reconstruct from individual parameters
        if (parameters.TryGetValue("name", out var nameObj)
            && parameters.TryGetValue("indicators", out var indicatorsObj)
            && parameters.TryGetValue("entryCondition", out var entryObj)
            && parameters.TryGetValue("exitCondition", out var exitObj))
        {
            try
            {
                var json = System.Text.Json.JsonSerializer.Serialize(parameters);
                return System.Text.Json.JsonSerializer.Deserialize<CompositeStrategyConfig>(
                    json,
                    new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            }
            catch
            {
                return null;
            }
        }

        return null;
    }

    #endregion
}
