using System.Globalization;
using System.Text;
using TradingResearchEngine.Application.Export;
using TradingResearchEngine.Application.Strategies;
using TradingResearchEngine.Application.Strategies.Composite;

namespace TradingResearchEngine.Infrastructure.Export;

/// <summary>
/// Exports a <see cref="StrategyVersion"/> to MetaTrader 4 Expert Advisor (.mq4) source code.
/// Uses template-based code generation with OnInit(), OnTick(), OnDeinit() structure.
/// </summary>
public sealed class MQL4StrategyExporter : IStrategyExporter
{
    private static readonly HashSet<string> SupportedStrategies = new(StringComparer.OrdinalIgnoreCase)
    {
        "moving-average-crossover",
        "volatility-scaled-trend",
        "zscore-mean-reversion",
        "stationary-mean-reversion",
        "donchian-breakout",
        "macro-regime",
        "composite"
    };

    /// <inheritdoc/>
    public ExportFormat Format => ExportFormat.MQL4;

    /// <inheritdoc/>
    public Task<ExportResult> ExportAsync(StrategyVersion version, CancellationToken ct)
    {
        var strategyType = version.BaseScenarioConfig.EffectiveStrategyConfig.StrategyType;

        if (!SupportedStrategies.Contains(strategyType))
        {
            var result = new ExportResult(
                ExportFormat.MQL4,
                string.Empty,
                string.Empty,
                new List<string> { $"Unsupported strategy type '{strategyType}' for MQL4 export." });
            return Task.FromResult(result);
        }

        var parameters = version.Parameters ?? new Dictionary<string, object>();

        // Handle composite strategy via CompositeExportHelper
        if (string.Equals(strategyType, "composite", StringComparison.OrdinalIgnoreCase))
        {
            var compositeConfig = CompositeExportHelper.ExtractCompositeConfig(parameters);
            if (compositeConfig is null)
            {
                var failResult = new ExportResult(
                    ExportFormat.MQL4,
                    string.Empty,
                    string.Empty,
                    new List<string> { "Could not extract CompositeStrategyConfig from strategy parameters." });
                return Task.FromResult(failResult);
            }

            var (compositeCode, compositeWarnings) = CompositeExportHelper.GenerateMQL4(compositeConfig);
            var compositeFileName = $"{SanitizeName(compositeConfig.Name)}_EA.mq4";
            var compositeResult = new ExportResult(ExportFormat.MQL4, compositeFileName, compositeCode, compositeWarnings);
            return Task.FromResult(compositeResult);
        }

        var code = GenerateCode(strategyType, parameters);
        var fileName = $"{SanitizeName(strategyType)}_EA.mq4";

        var exportResult = new ExportResult(
            ExportFormat.MQL4,
            fileName,
            code,
            Array.Empty<string>().ToList());

        return Task.FromResult(exportResult);
    }

    private static string GenerateCode(string strategyType, Dictionary<string, object> parameters)
    {
        return strategyType switch
        {
            "moving-average-crossover" => GenerateMovingAverageCrossover(parameters),
            "volatility-scaled-trend" => GenerateVolatilityScaledTrend(parameters),
            "zscore-mean-reversion" => GenerateZScoreMeanReversion(parameters),
            "stationary-mean-reversion" => GenerateStationaryMeanReversion(parameters),
            "donchian-breakout" => GenerateDonchianBreakout(parameters),
            "macro-regime" => GenerateMacroRegime(parameters),
            _ => string.Empty
        };
    }

    private static string GenerateMovingAverageCrossover(Dictionary<string, object> parameters)
    {
        var fast = GetIntParam(parameters, "fastPeriod", 12);
        var slow = GetIntParam(parameters, "slowPeriod", 26);

        return $@"//+------------------------------------------------------------------+
//| Moving Average Crossover EA                                       |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: Signal timing may differ from backtest due to MQL4 tick-based execution
input int FastPeriod = {fast};
input int SlowPeriod = {slow};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double fastMA = iMA(Symbol(), 0, FastPeriod, 0, MODE_SMA, PRICE_CLOSE, 0);
    double slowMA = iMA(Symbol(), 0, SlowPeriod, 0, MODE_SMA, PRICE_CLOSE, 0);
    double prevFastMA = iMA(Symbol(), 0, FastPeriod, 0, MODE_SMA, PRICE_CLOSE, 1);
    double prevSlowMA = iMA(Symbol(), 0, SlowPeriod, 0, MODE_SMA, PRICE_CLOSE, 1);

    // Bullish crossover
    if (prevFastMA <= prevSlowMA && fastMA > slowMA)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""MA Cross Buy"", 0, 0, clrGreen);
    }}
    // Bearish crossover — close position
    else if (prevFastMA >= prevSlowMA && fastMA < slowMA)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static string GenerateVolatilityScaledTrend(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var atrPeriod = GetIntParam(parameters, "atrPeriod", 14);
        var atrMultiplier = GetDecimalParam(parameters, "atrMultiplier", 2.0m);

        return $@"//+------------------------------------------------------------------+
//| Volatility Scaled Trend EA                                        |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: Position sizing based on ATR may differ from backtest risk layer
input int TrendPeriod = {period};
input int AtrPeriod = {atrPeriod};
input double AtrMultiplier = {Fmt(atrMultiplier)};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double ma = iMA(Symbol(), 0, TrendPeriod, 0, MODE_SMA, PRICE_CLOSE, 0);
    double atr = iATR(Symbol(), 0, AtrPeriod, 0);
    double price = Close[0];

    // Enter long when price is above MA + ATR threshold
    if (price > ma + atr * AtrMultiplier)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""Vol Trend Buy"", 0, 0, clrGreen);
    }}
    // Exit when price drops below MA
    else if (price < ma)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static string GenerateZScoreMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//+------------------------------------------------------------------+
//| Z-Score Mean Reversion EA                                         |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: Z-score computation uses iStdDev; slight numerical differences possible
input int Period = {period};
input double EntryThreshold = {Fmt(entryThreshold)};
input double ExitThreshold = {Fmt(exitThreshold)};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double ma = iMA(Symbol(), 0, Period, 0, MODE_SMA, PRICE_CLOSE, 0);
    double stdDev = iStdDev(Symbol(), 0, Period, 0, MODE_SMA, PRICE_CLOSE, 0);
    double price = Close[0];

    if (stdDev == 0) return;

    double zScore = (price - ma) / stdDev;

    // Enter long when z-score is below entry threshold (oversold)
    if (zScore <= EntryThreshold)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""ZScore Buy"", 0, 0, clrGreen);
    }}
    // Exit when z-score reverts above exit threshold
    else if (zScore >= ExitThreshold)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static string GenerateStationaryMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//+------------------------------------------------------------------+
//| Stationary Mean Reversion EA                                      |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: ADF stationarity test is not available in MQL4; strategy assumes stationarity holds
input int Period = {period};
input double EntryThreshold = {Fmt(entryThreshold)};
input double ExitThreshold = {Fmt(exitThreshold)};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double ma = iMA(Symbol(), 0, Period, 0, MODE_SMA, PRICE_CLOSE, 0);
    double stdDev = iStdDev(Symbol(), 0, Period, 0, MODE_SMA, PRICE_CLOSE, 0);
    double price = Close[0];

    if (stdDev == 0) return;

    double deviation = (price - ma) / stdDev;

    // Enter long when deviation is below entry threshold
    if (deviation <= EntryThreshold)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""Stationary MR Buy"", 0, 0, clrGreen);
    }}
    // Exit when deviation reverts above exit threshold
    else if (deviation >= ExitThreshold)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static string GenerateDonchianBreakout(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);

        return $@"//+------------------------------------------------------------------+
//| Donchian Breakout EA                                              |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: Donchian channel computed manually; slight differences from iCustom possible
input int Period = {period};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double upperChannel = High[iHighest(Symbol(), 0, MODE_HIGH, Period, 1)];
    double lowerChannel = Low[iLowest(Symbol(), 0, MODE_LOW, Period, 1)];
    double price = Close[0];

    // Enter long on upper channel breakout
    if (price > upperChannel)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""Donchian Buy"", 0, 0, clrGreen);
    }}
    // Exit on lower channel break
    else if (price < lowerChannel)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static string GenerateMacroRegime(Dictionary<string, object> parameters)
    {
        var shortPeriod = GetIntParam(parameters, "shortPeriod", 50);
        var longPeriod = GetIntParam(parameters, "longPeriod", 200);

        return $@"//+------------------------------------------------------------------+
//| Macro Regime EA                                                   |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict

// NOTE: Macro regime detection is simplified; backtest uses additional regime indicators
input int ShortPeriod = {shortPeriod};
input int LongPeriod = {longPeriod};
input double LotSize = 0.1;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double shortMA = iMA(Symbol(), 0, ShortPeriod, 0, MODE_SMA, PRICE_CLOSE, 0);
    double longMA = iMA(Symbol(), 0, LongPeriod, 0, MODE_SMA, PRICE_CLOSE, 0);

    // Bullish regime: short MA above long MA
    if (shortMA > longMA)
    {{
        if (OrdersTotal() == 0)
            OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, 0, 0, ""Regime Buy"", 0, 0, clrGreen);
    }}
    // Bearish regime: exit
    else if (shortMA < longMA)
    {{
        for (int i = OrdersTotal() - 1; i >= 0; i--)
        {{
            if (OrderSelect(i, SELECT_BY_POS) && OrderSymbol() == Symbol())
                OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
        }}
    }}
}}
";
    }

    private static int GetIntParam(Dictionary<string, object> parameters, string key, int defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                int i => i,
                long l => (int)l,
                double d => (int)d,
                decimal dec => (int)dec,
                string s when int.TryParse(s, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetInt32(out var ji) => ji,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static decimal GetDecimalParam(Dictionary<string, object> parameters, string key, decimal defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                decimal d => d,
                double dbl => (decimal)dbl,
                float f => (decimal)f,
                int i => i,
                long l => l,
                string s when decimal.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetDecimal(out var jd) => jd,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static string Fmt(decimal value) => value.ToString(CultureInfo.InvariantCulture);

    private static string SanitizeName(string strategyType) =>
        strategyType.Replace("-", "_");
}
