using System.Globalization;
using System.Text;
using TradingResearchEngine.Application.Export;
using TradingResearchEngine.Application.Strategy;
using TradingResearchEngine.Application.Strategy.Composite;

namespace TradingResearchEngine.Infrastructure.Export;

/// <summary>
/// Exports a <see cref="StrategyVersion"/> to MetaTrader 5 Expert Advisor (.mq5) source code.
/// Uses CTrade class pattern with OnTick() and OnTrade() structure.
/// </summary>
public sealed class MQL5StrategyExporter : IStrategyExporter
{
    private static readonly HashSet<string> SupportedStrategies = new(StringComparer.OrdinalIgnoreCase)
    {
        "moving-average-crossover",
        "volatility-scaled-trend",
        "zscore-mean-reversion",
        "stationary-mean-reversion",
        "donchian-breakout",
        "macro-regime",
        "composite"
    };

    /// <inheritdoc/>
    public ExportFormat Format => ExportFormat.MQL5;

    /// <inheritdoc/>
    public Task<ExportResult> ExportAsync(StrategyVersion version, CancellationToken ct)
    {
        var strategyType = version.BaseScenarioConfig.EffectiveStrategyConfig.StrategyType;

        if (!SupportedStrategies.Contains(strategyType))
        {
            var result = new ExportResult(
                ExportFormat.MQL5,
                string.Empty,
                string.Empty,
                new List<string> { $"Unsupported strategy type '{strategyType}' for MQL5 export." });
            return Task.FromResult(result);
        }

        var parameters = version.Parameters ?? new Dictionary<string, object>();

        // Handle composite strategy via CompositeExportHelper
        if (string.Equals(strategyType, "composite", StringComparison.OrdinalIgnoreCase))
        {
            var compositeConfig = CompositeExportHelper.ExtractCompositeConfig(parameters);
            if (compositeConfig is null)
            {
                var failResult = new ExportResult(
                    ExportFormat.MQL5,
                    string.Empty,
                    string.Empty,
                    new List<string> { "Could not extract CompositeStrategyConfig from strategy parameters." });
                return Task.FromResult(failResult);
            }

            var (compositeCode, compositeWarnings) = CompositeExportHelper.GenerateMQL5(compositeConfig);
            var compositeFileName = $"{SanitizeName(compositeConfig.Name)}_EA.mq5";
            var compositeResult = new ExportResult(ExportFormat.MQL5, compositeFileName, compositeCode, compositeWarnings);
            return Task.FromResult(compositeResult);
        }

        var code = GenerateCode(strategyType, parameters);
        var fileName = $"{SanitizeName(strategyType)}_EA.mq5";

        var exportResult = new ExportResult(
            ExportFormat.MQL5,
            fileName,
            code,
            Array.Empty<string>().ToList());

        return Task.FromResult(exportResult);
    }

    private static string GenerateCode(string strategyType, Dictionary<string, object> parameters)
    {
        return strategyType switch
        {
            "moving-average-crossover" => GenerateMovingAverageCrossover(parameters),
            "volatility-scaled-trend" => GenerateVolatilityScaledTrend(parameters),
            "zscore-mean-reversion" => GenerateZScoreMeanReversion(parameters),
            "stationary-mean-reversion" => GenerateStationaryMeanReversion(parameters),
            "donchian-breakout" => GenerateDonchianBreakout(parameters),
            "macro-regime" => GenerateMacroRegime(parameters),
            _ => string.Empty
        };
    }

    private static string GenerateMovingAverageCrossover(Dictionary<string, object> parameters)
    {
        var fast = GetIntParam(parameters, "fastPeriod", 12);
        var slow = GetIntParam(parameters, "slowPeriod", 26);

        return $@"//+------------------------------------------------------------------+
//| Moving Average Crossover EA (MQL5)                                |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: Signal timing may differ from backtest due to MQL5 tick-based execution
input int FastPeriod = {fast};
input int SlowPeriod = {slow};
input double LotSize = 0.1;

CTrade trade;
int handleFast;
int handleSlow;

int OnInit()
{{
    handleFast = iMA(Symbol(), PERIOD_CURRENT, FastPeriod, 0, MODE_SMA, PRICE_CLOSE);
    handleSlow = iMA(Symbol(), PERIOD_CURRENT, SlowPeriod, 0, MODE_SMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    IndicatorRelease(handleFast);
    IndicatorRelease(handleSlow);
}}

void OnTick()
{{
    double fastMA[2], slowMA[2];
    CopyBuffer(handleFast, 0, 0, 2, fastMA);
    CopyBuffer(handleSlow, 0, 0, 2, slowMA);

    // Bullish crossover
    if (fastMA[0] > slowMA[0] && fastMA[1] <= slowMA[1])
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""MA Cross Buy"");
    }}
    // Bearish crossover — close position
    else if (fastMA[0] < slowMA[0] && fastMA[1] >= slowMA[1])
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static string GenerateVolatilityScaledTrend(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var atrPeriod = GetIntParam(parameters, "atrPeriod", 14);
        var atrMultiplier = GetDecimalParam(parameters, "atrMultiplier", 2.0m);

        return $@"//+------------------------------------------------------------------+
//| Volatility Scaled Trend EA (MQL5)                                 |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: Position sizing based on ATR may differ from backtest risk layer
input int TrendPeriod = {period};
input int AtrPeriod = {atrPeriod};
input double AtrMultiplier = {Fmt(atrMultiplier)};
input double LotSize = 0.1;

CTrade trade;
int handleMA;
int handleATR;

int OnInit()
{{
    handleMA = iMA(Symbol(), PERIOD_CURRENT, TrendPeriod, 0, MODE_SMA, PRICE_CLOSE);
    handleATR = iATR(Symbol(), PERIOD_CURRENT, AtrPeriod);
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    IndicatorRelease(handleMA);
    IndicatorRelease(handleATR);
}}

void OnTick()
{{
    double ma[1], atr[1];
    CopyBuffer(handleMA, 0, 0, 1, ma);
    CopyBuffer(handleATR, 0, 0, 1, atr);
    double price = SymbolInfoDouble(Symbol(), SYMBOL_LAST);

    // Enter long when price is above MA + ATR threshold
    if (price > ma[0] + atr[0] * AtrMultiplier)
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""Vol Trend Buy"");
    }}
    // Exit when price drops below MA
    else if (price < ma[0])
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static string GenerateZScoreMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//+------------------------------------------------------------------+
//| Z-Score Mean Reversion EA (MQL5)                                  |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: Z-score computation uses iStdDev; slight numerical differences possible
input int Period = {period};
input double EntryThreshold = {Fmt(entryThreshold)};
input double ExitThreshold = {Fmt(exitThreshold)};
input double LotSize = 0.1;

CTrade trade;
int handleMA;
int handleStdDev;

int OnInit()
{{
    handleMA = iMA(Symbol(), PERIOD_CURRENT, Period, 0, MODE_SMA, PRICE_CLOSE);
    handleStdDev = iStdDev(Symbol(), PERIOD_CURRENT, Period, 0, MODE_SMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    IndicatorRelease(handleMA);
    IndicatorRelease(handleStdDev);
}}

void OnTick()
{{
    double ma[1], stdDev[1];
    CopyBuffer(handleMA, 0, 0, 1, ma);
    CopyBuffer(handleStdDev, 0, 0, 1, stdDev);
    double price = SymbolInfoDouble(Symbol(), SYMBOL_LAST);

    if (stdDev[0] == 0) return;

    double zScore = (price - ma[0]) / stdDev[0];

    // Enter long when z-score is below entry threshold (oversold)
    if (zScore <= EntryThreshold)
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""ZScore Buy"");
    }}
    // Exit when z-score reverts above exit threshold
    else if (zScore >= ExitThreshold)
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static string GenerateStationaryMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//+------------------------------------------------------------------+
//| Stationary Mean Reversion EA (MQL5)                               |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: ADF stationarity test is not available in MQL5; strategy assumes stationarity holds
input int Period = {period};
input double EntryThreshold = {Fmt(entryThreshold)};
input double ExitThreshold = {Fmt(exitThreshold)};
input double LotSize = 0.1;

CTrade trade;
int handleMA;
int handleStdDev;

int OnInit()
{{
    handleMA = iMA(Symbol(), PERIOD_CURRENT, Period, 0, MODE_SMA, PRICE_CLOSE);
    handleStdDev = iStdDev(Symbol(), PERIOD_CURRENT, Period, 0, MODE_SMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    IndicatorRelease(handleMA);
    IndicatorRelease(handleStdDev);
}}

void OnTick()
{{
    double ma[1], stdDev[1];
    CopyBuffer(handleMA, 0, 0, 1, ma);
    CopyBuffer(handleStdDev, 0, 0, 1, stdDev);
    double price = SymbolInfoDouble(Symbol(), SYMBOL_LAST);

    if (stdDev[0] == 0) return;

    double deviation = (price - ma[0]) / stdDev[0];

    // Enter long when deviation is below entry threshold
    if (deviation <= EntryThreshold)
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""Stationary MR Buy"");
    }}
    // Exit when deviation reverts above exit threshold
    else if (deviation >= ExitThreshold)
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static string GenerateDonchianBreakout(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);

        return $@"//+------------------------------------------------------------------+
//| Donchian Breakout EA (MQL5)                                       |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: Donchian channel computed manually via iHighest/iLowest
input int Period = {period};
input double LotSize = 0.1;

CTrade trade;

int OnInit()
{{
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    // Cleanup
}}

void OnTick()
{{
    double upperChannel = 0, lowerChannel = DBL_MAX;
    for (int i = 1; i <= Period; i++)
    {{
        double high = iHigh(Symbol(), PERIOD_CURRENT, i);
        double low = iLow(Symbol(), PERIOD_CURRENT, i);
        if (high > upperChannel) upperChannel = high;
        if (low < lowerChannel) lowerChannel = low;
    }}

    double price = SymbolInfoDouble(Symbol(), SYMBOL_LAST);

    // Enter long on upper channel breakout
    if (price > upperChannel)
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""Donchian Buy"");
    }}
    // Exit on lower channel break
    else if (price < lowerChannel)
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static string GenerateMacroRegime(Dictionary<string, object> parameters)
    {
        var shortPeriod = GetIntParam(parameters, "shortPeriod", 50);
        var longPeriod = GetIntParam(parameters, "longPeriod", 200);

        return $@"//+------------------------------------------------------------------+
//| Macro Regime EA (MQL5)                                            |
//| Generated by TradingResearchEngine                                |
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>

// NOTE: Macro regime detection is simplified; backtest uses additional regime indicators
input int ShortPeriod = {shortPeriod};
input int LongPeriod = {longPeriod};
input double LotSize = 0.1;

CTrade trade;
int handleShort;
int handleLong;

int OnInit()
{{
    handleShort = iMA(Symbol(), PERIOD_CURRENT, ShortPeriod, 0, MODE_SMA, PRICE_CLOSE);
    handleLong = iMA(Symbol(), PERIOD_CURRENT, LongPeriod, 0, MODE_SMA, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
    IndicatorRelease(handleShort);
    IndicatorRelease(handleLong);
}}

void OnTick()
{{
    double shortMA[1], longMA[1];
    CopyBuffer(handleShort, 0, 0, 1, shortMA);
    CopyBuffer(handleLong, 0, 0, 1, longMA);

    // Bullish regime: short MA above long MA
    if (shortMA[0] > longMA[0])
    {{
        if (PositionsTotal() == 0)
            trade.Buy(LotSize, Symbol(), 0, 0, 0, ""Regime Buy"");
    }}
    // Bearish regime: exit
    else if (shortMA[0] < longMA[0])
    {{
        for (int i = PositionsTotal() - 1; i >= 0; i--)
        {{
            if (PositionGetSymbol(i) == Symbol())
                trade.PositionClose(PositionGetTicket(i));
        }}
    }}
}}

void OnTrade()
{{
    // Trade event handler for position management
}}
";
    }

    private static int GetIntParam(Dictionary<string, object> parameters, string key, int defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                int i => i,
                long l => (int)l,
                double d => (int)d,
                decimal dec => (int)dec,
                string s when int.TryParse(s, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetInt32(out var ji) => ji,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static decimal GetDecimalParam(Dictionary<string, object> parameters, string key, decimal defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                decimal d => d,
                double dbl => (decimal)dbl,
                float f => (decimal)f,
                int i => i,
                long l => l,
                string s when decimal.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetDecimal(out var jd) => jd,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static string Fmt(decimal value) => value.ToString(CultureInfo.InvariantCulture);

    private static string SanitizeName(string strategyType) =>
        strategyType.Replace("-", "_");
}
