using System.Globalization;
using System.Text;
using TradingResearchEngine.Application.Export;
using TradingResearchEngine.Application.Strategy;

namespace TradingResearchEngine.Infrastructure.Export;

/// <summary>
/// Exports a <see cref="StrategyVersion"/> to TradingView Pine Script v6 (.pine) source code.
/// Uses strategy(), ta.* functions, strategy.entry(), and strategy.close() patterns.
/// </summary>
public sealed class PineScriptExporter : IStrategyExporter
{
    private static readonly HashSet<string> SupportedStrategies = new(StringComparer.OrdinalIgnoreCase)
    {
        "moving-average-crossover",
        "volatility-scaled-trend",
        "zscore-mean-reversion",
        "stationary-mean-reversion",
        "donchian-breakout",
        "macro-regime"
    };

    /// <inheritdoc/>
    public ExportFormat Format => ExportFormat.PineScript;

    /// <inheritdoc/>
    public Task<ExportResult> ExportAsync(StrategyVersion version, CancellationToken ct)
    {
        var strategyType = version.BaseScenarioConfig.EffectiveStrategyConfig.StrategyType;

        if (!SupportedStrategies.Contains(strategyType))
        {
            var result = new ExportResult(
                ExportFormat.PineScript,
                string.Empty,
                string.Empty,
                new List<string> { $"Unsupported strategy type '{strategyType}' for PineScript export." });
            return Task.FromResult(result);
        }

        var parameters = version.Parameters ?? new Dictionary<string, object>();
        var code = GenerateCode(strategyType, parameters);
        var fileName = $"{SanitizeName(strategyType)}.pine";

        var exportResult = new ExportResult(
            ExportFormat.PineScript,
            fileName,
            code,
            Array.Empty<string>().ToList());

        return Task.FromResult(exportResult);
    }

    private static string GenerateCode(string strategyType, Dictionary<string, object> parameters)
    {
        return strategyType switch
        {
            "moving-average-crossover" => GenerateMovingAverageCrossover(parameters),
            "volatility-scaled-trend" => GenerateVolatilityScaledTrend(parameters),
            "zscore-mean-reversion" => GenerateZScoreMeanReversion(parameters),
            "stationary-mean-reversion" => GenerateStationaryMeanReversion(parameters),
            "donchian-breakout" => GenerateDonchianBreakout(parameters),
            "macro-regime" => GenerateMacroRegime(parameters),
            _ => string.Empty
        };
    }

    private static string GenerateMovingAverageCrossover(Dictionary<string, object> parameters)
    {
        var fast = GetIntParam(parameters, "fastPeriod", 12);
        var slow = GetIntParam(parameters, "slowPeriod", 26);

        return $@"//@version=6
// Moving Average Crossover Strategy
// Generated by TradingResearchEngine
// NOTE: Signal timing aligns with bar close; backtest uses next-bar-open fill by default
strategy(""MA Crossover"", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

fastPeriod = input.int({fast}, ""Fast Period"")
slowPeriod = input.int({slow}, ""Slow Period"")

fastMA = ta.sma(close, fastPeriod)
slowMA = ta.sma(close, slowPeriod)

// Bullish crossover
longCondition = ta.crossover(fastMA, slowMA)
// Bearish crossover
exitCondition = ta.crossunder(fastMA, slowMA)

if longCondition
    strategy.entry(""Long"", strategy.long)

if exitCondition
    strategy.close(""Long"")

plot(fastMA, ""Fast MA"", color=color.blue)
plot(slowMA, ""Slow MA"", color=color.red)
";
    }

    private static string GenerateVolatilityScaledTrend(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var atrPeriod = GetIntParam(parameters, "atrPeriod", 14);
        var atrMultiplier = GetDecimalParam(parameters, "atrMultiplier", 2.0m);

        return $@"//@version=6
// Volatility Scaled Trend Strategy
// Generated by TradingResearchEngine
// NOTE: Position sizing based on ATR may differ from backtest risk layer
strategy(""Vol Scaled Trend"", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

trendPeriod = input.int({period}, ""Trend Period"")
atrPeriod = input.int({atrPeriod}, ""ATR Period"")
atrMult = input.float({Fmt(atrMultiplier)}, ""ATR Multiplier"")

ma = ta.sma(close, trendPeriod)
atr = ta.atr(atrPeriod)

// Enter long when price is above MA + ATR threshold
longCondition = close > ma + atr * atrMult
// Exit when price drops below MA
exitCondition = close < ma

if longCondition and strategy.position_size == 0
    strategy.entry(""Long"", strategy.long)

if exitCondition and strategy.position_size > 0
    strategy.close(""Long"")

plot(ma, ""Trend MA"", color=color.blue)
plot(ma + atr * atrMult, ""Upper Band"", color=color.green)
";
    }

    private static string GenerateZScoreMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//@version=6
// Z-Score Mean Reversion Strategy
// Generated by TradingResearchEngine
// NOTE: Z-score computation uses ta.stdev; slight numerical differences possible
strategy(""ZScore Mean Reversion"", overlay=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

period = input.int({period}, ""Period"")
entryThresh = input.float({Fmt(entryThreshold)}, ""Entry Threshold"")
exitThresh = input.float({Fmt(exitThreshold)}, ""Exit Threshold"")

ma = ta.sma(close, period)
stdDev = ta.stdev(close, period)
zScore = (close - ma) / stdDev

// Enter long when z-score is below entry threshold (oversold)
longCondition = zScore <= entryThresh
// Exit when z-score reverts above exit threshold
exitCondition = zScore >= exitThresh

if longCondition and strategy.position_size == 0
    strategy.entry(""Long"", strategy.long)

if exitCondition and strategy.position_size > 0
    strategy.close(""Long"")

plot(zScore, ""Z-Score"", color=color.purple)
hline(entryThresh, ""Entry"", color=color.green)
hline(exitThresh, ""Exit"", color=color.red)
";
    }

    private static string GenerateStationaryMeanReversion(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);
        var entryThreshold = GetDecimalParam(parameters, "entryThreshold", -2.0m);
        var exitThreshold = GetDecimalParam(parameters, "exitThreshold", 0.0m);

        return $@"//@version=6
// Stationary Mean Reversion Strategy
// Generated by TradingResearchEngine
// NOTE: ADF stationarity test is not available in Pine Script; strategy assumes stationarity holds
strategy(""Stationary Mean Reversion"", overlay=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

period = input.int({period}, ""Period"")
entryThresh = input.float({Fmt(entryThreshold)}, ""Entry Threshold"")
exitThresh = input.float({Fmt(exitThreshold)}, ""Exit Threshold"")

ma = ta.sma(close, period)
stdDev = ta.stdev(close, period)
deviation = (close - ma) / stdDev

// Enter long when deviation is below entry threshold
longCondition = deviation <= entryThresh
// Exit when deviation reverts above exit threshold
exitCondition = deviation >= exitThresh

if longCondition and strategy.position_size == 0
    strategy.entry(""Long"", strategy.long)

if exitCondition and strategy.position_size > 0
    strategy.close(""Long"")

plot(deviation, ""Deviation"", color=color.purple)
hline(entryThresh, ""Entry"", color=color.green)
hline(exitThresh, ""Exit"", color=color.red)
";
    }

    private static string GenerateDonchianBreakout(Dictionary<string, object> parameters)
    {
        var period = GetIntParam(parameters, "period", 20);

        return $@"//@version=6
// Donchian Breakout Strategy
// Generated by TradingResearchEngine
// NOTE: Donchian channel uses ta.highest/ta.lowest; matches backtest logic closely
strategy(""Donchian Breakout"", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

period = input.int({period}, ""Period"")

upperChannel = ta.highest(high, period)[1]
lowerChannel = ta.lowest(low, period)[1]

// Enter long on upper channel breakout
longCondition = close > upperChannel
// Exit on lower channel break
exitCondition = close < lowerChannel

if longCondition and strategy.position_size == 0
    strategy.entry(""Long"", strategy.long)

if exitCondition and strategy.position_size > 0
    strategy.close(""Long"")

plot(upperChannel, ""Upper"", color=color.green)
plot(lowerChannel, ""Lower"", color=color.red)
";
    }

    private static string GenerateMacroRegime(Dictionary<string, object> parameters)
    {
        var shortPeriod = GetIntParam(parameters, "shortPeriod", 50);
        var longPeriod = GetIntParam(parameters, "longPeriod", 200);

        return $@"//@version=6
// Macro Regime Strategy
// Generated by TradingResearchEngine
// NOTE: Macro regime detection is simplified; backtest uses additional regime indicators
strategy(""Macro Regime"", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

shortPeriod = input.int({shortPeriod}, ""Short Period"")
longPeriod = input.int({longPeriod}, ""Long Period"")

shortMA = ta.sma(close, shortPeriod)
longMA = ta.sma(close, longPeriod)

// Bullish regime: short MA above long MA
longCondition = ta.crossover(shortMA, longMA)
// Bearish regime: exit
exitCondition = ta.crossunder(shortMA, longMA)

if longCondition
    strategy.entry(""Long"", strategy.long)

if exitCondition
    strategy.close(""Long"")

plot(shortMA, ""Short MA"", color=color.blue)
plot(longMA, ""Long MA"", color=color.red)
";
    }

    private static int GetIntParam(Dictionary<string, object> parameters, string key, int defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                int i => i,
                long l => (int)l,
                double d => (int)d,
                decimal dec => (int)dec,
                string s when int.TryParse(s, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetInt32(out var ji) => ji,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static decimal GetDecimalParam(Dictionary<string, object> parameters, string key, decimal defaultValue)
    {
        if (parameters.TryGetValue(key, out var value))
        {
            return value switch
            {
                decimal d => d,
                double dbl => (decimal)dbl,
                float f => (decimal)f,
                int i => i,
                long l => l,
                string s when decimal.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed) => parsed,
                System.Text.Json.JsonElement je when je.TryGetDecimal(out var jd) => jd,
                _ => defaultValue
            };
        }
        return defaultValue;
    }

    private static string Fmt(decimal value) => value.ToString(CultureInfo.InvariantCulture);

    private static string SanitizeName(string strategyType) =>
        strategyType.Replace("-", "_");
}
