namespace TradingResearchEngine.Application.AI;

/// <summary>
/// The result of an LLM-based translation of a natural-language strategy description
/// into a structured strategy configuration.
/// </summary>
/// <param name="Success">
/// Whether the translation succeeded and produced a usable configuration.
/// </param>
/// <param name="SelectedTemplateId">
/// The template ID selected by the LLM as the best match for the user's description,
/// or <c>null</c> if no template was selected.
/// </param>
/// <param name="StrategyType">
/// The strategy type name (kebab-case) corresponding to the selected template,
/// or <c>null</c> if the LLM could not determine a type.
/// </param>
/// <param name="SuggestedParameters">
/// A dictionary of parameter names to suggested values, constrained by the strategy's
/// parameter schema bounds. <c>null</c> when translation fails.
/// </param>
/// <param name="SuggestedHypothesis">
/// A concise hypothesis statement generated by the LLM describing the market assumption
/// behind the strategy, or <c>null</c> if not generated.
/// </param>
/// <param name="SuggestedTimeframe">
/// The recommended timeframe (e.g. "Daily", "H4", "H1") for the strategy,
/// or <c>null</c> if not determined.
/// </param>
/// <param name="FailureReason">
/// A human-readable explanation of why translation failed, or <c>null</c> on success.
/// </param>
/// <param name="GeneratedStrategyCode">
/// Optional C# source code for a custom <c>IStrategy</c> implementation generated by the LLM
/// when no existing template is a suitable match. <c>null</c> when a template is selected.
/// </param>
public sealed record StrategyIdeaResult(
    bool Success,
    string? SelectedTemplateId = null,
    string? StrategyType = null,
    Dictionary<string, object>? SuggestedParameters = null,
    string? SuggestedHypothesis = null,
    string? SuggestedTimeframe = null,
    string? FailureReason = null,
    string? GeneratedStrategyCode = null);
